# Generated by Django 4.1.2 on 2022-11-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualStock',
        ),
    ]
